### PR TITLE
typescript ver: hardhat kit

### PR DESCRIPTION
**Pull request by xBalbinus**
Purpose:

The current FEVM hardhat starter kit does not have typescript support. 

Solution:

This PR adds typescript support for the FEVM Hardhat starter kit, with a deploy script and original contracts in typescript

Changelog:
- Tested deployments and changes
- Prefer to have this on a separate branch ( Typescript specific )

### CODE REVIEW

**Review by dellwatson — COMMENTED** [review]
love the ts

**Comment by xBalbinus** [comment]
@dellwatson I'll clean this up a little bit, rebase / merge on main and please lmk if you have any feedback!

**Review by ZakAyesh — COMMENTED** [review]
Love the idea of having a typescript version of the kit on another branch (and we can possibly make its own repo down the road). We would like to keep the code as close as possible to the current JS kit, but just add the basics for typescript for now. Can you make sure, for now, that we do the minimum to update to typescript but mirror the main branch?

**Comment by xBalbinus** [comment]
Has been updated to mirror the main branch

**Review by ZakAyesh — APPROVED** [review]
Sorry for the delay here, most of the files look good here. I will be merging this into a separate typescript branch. Some clean up will be necessary for some things (the readme for example) but we can clean those up after this PR. 

Thanks for the great work!

**Comment by xBalbinus** [comment]
No problem! I notice a typescript branch on the repo now, so please let me
know if I may help out with any other things like polishing up that readme.

**Pull request merged**
